config/routes.rb
Rails.application.routes.draw do
 

     resources :students
     resources :colleges
   

end

app/models/college.rb
class College < ActiveRecord::Base
	has_many :students

	validates :name, presence: true, uniqueness: true, format: {with: /\A[a-zA-Z|\s]+\Z/}
    validates :location, presence: true
    validates :email, presence: true, format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i}, uniqueness: true
    validates :phno, presence: true, numericality: true, length: {minimum:10 , maximum:10}
end

app/models/student.rb
class Student < ActiveRecord::Base
	belongs_to :college

	validates :name,presence:true,uniqueness:true,format:{with:/\A[a-zA-Z]+\z/,message:"enter valid name"}
	validates :email,presence:true,uniqueness:true,format:{with:/\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/,message:"enter valid email"}
	validates :dob,presence:true,format:{with:/\d{2}\/\d{2}\/\d{4}/,message:"dob must be in format"}
	validates :age,presence:true,numericality:true
	# validates :college_id,presence:true,numericality:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
   protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }
end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
	def new
		@college = College.new
	end

	def index
		@colleges = College.all
		render json: {success: true, message: "All colleges selected",college: @colleges}
	end

	def show
		@college = College.find(params[:id])
		render json: {success: true, message: "a college is selected",college: @college}
	end

	def create
		@college = College.new(college_params)
      	if @college.save
       		 render json: {success: true, message: "college has been created",college: @college} 
       		# redirect_to colleges_path
      	else
      		 render json: {success: false, message: "college hasnot been created",errors: @college.errors.full_messages} 
      		# render 'new'
      	end
	end

	def edit
		@college = College.find(params[:id])
		render json: {success: true,message: "Selected college is edited successfully",college: @college}
	end

	def update
		@college = College.find(params[:id])
		if @college.update(college_params)
		    render json: {success: true,message: "selected college has been updated",college: @college} 
			# redirect_to colleges_path
		else
			render json: {success: false, message: "selected college hasnot been selected",errors: @college.errors.full_messages} 
			# render "edit"
		end
	end

	def destroy
		@college = College.find(params[:id])
		if @college.destroy
			render json: {success: true, message: "Selected college has been deleted",college: @college}
		else
			render json: {success: false, message: "Selected college has been deleted",errors: @college.errors.full_messages}
		end
	end

	private 
		def college_params
			#if we pass params then test cases will work
			params.permit(:name,:email,:phno,:location)
		end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	def new
		@colleges = College.all
		@student = Student.new
	end

	def create
		@colleges = College.all
		@student = Student.new(student_params)
      if @student.save
       	render json: {success: true,message: "student has been created",student: @student}
       	# redirect_to students_path
      else
      	render json: {success: true,message: "student has not been created",errors: @student.errors.full_messages}
      	# render "new"
      end
    
	end

	def index
		# @college = College.find(params[:college_id])
		@colleges = College.all
		@students = Student.all
		render json: {success: true,message: "All students",students: @students}
		# @student = Student.find(params[:id])
		# @college = @student.college.id
	end

	def show
		@colleges = College.all
		@student = Student.find(params[:id])
		# raise @student.college_id.inspect
		@college = College.find_by(params[@student.college_id])
		render json: {success: true,message: "required student",student: @student}
	end

	def edit
		@colleges = College.all
		@student = Student.find(params[:id])
	end

	def update
		@colleges = College.all
		@student = Student.find(params[:id])
		if @student.update(student_params)
			render json: {success: true,message: "student has been updated",student: @student}
		else
			render json: {success: false,message: "student has not been updated",errors: @student.errors.full_messages}
		end
	end

	def destroy
		@colleges = College.all
		@student = Student.find(params[:id])
		if @student.destroy
			render json: {success: true,message: "student has been deleted",student: @student}
		else
			render json: {success: false,message: "student has not been deleted",errors: @student.errors.full_messages}
		end	
	end

	private
		def student_params
			params.permit(:name,:email,:dob,:age,:college_id)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/colleges/_form.html.erb
<style>
	.clr{color:red;}
</style>

<div class="container">
<center><h2 class="text-danger">New College</h2></center>
<hr/>
	<div class="form-horizontal">
		<%= form_for @college do |c| %>
			
			<div class="form-group ">
				<%= c.label :College,class:"control-label col-sm-3"%>
			<div class="col-sm-6">
				<%= c.text_field :name,class:"form-control",id:"title"%>
				<div id = "titleid"class = "clr"></div>
				<div class="hidden"id = "idi"><span class="glyphicon glyphicon-ok"></span></div>
			</div>
			</div>

			<div>
			

			<div class="form-group">
				<%= c.label :Email,class:"control-label col-sm-3"%>
			<div class="col-sm-6">
				<%= c.email_field :email,class:"form-control"%>
			</div>
			</div>

			<div class="form-group">
				<%= c.label :Location,class:"control-label col-sm-3"%>
			<div class="col-sm-6">
				<%= c.text_field :location,class:"form-control"%>
			</div>
			</div>

			<div class="form-group">
				<%= c.label :Phone_Number,class:"control-label col-sm-3"%>
			<div class="col-sm-6">
				<%= c.text_field :phno,class:"form-control"%>
			</div>
			</div>



			<div class="form-group">
				<%= c.submit "Save",class:"col-sm-offset-3 btn btn-sm btn-info"%>
				<%= link_to "All Colleges",colleges_path,class:"btn btn-sm btn-info col-sm-offset-0"%>
			</div>	

		<%end%>

		<% if @college.errors.present? %>
		    <div id="error_explanation">
		      <h3 class="text-danger">
		        <%= pluralize(@college.errors.count, "error") %> prohibited
		        this article from being saved:
		      </h3>
		      
		      <ul>
		        <% @college.errors.full_messages.each do |msg| %>
		          <div class="alert alert-danger">
		          	<li><%= msg %></li>
		          </div>
		        <% end %>
		      </ul>
		    
		    </div>
  		<% end %>

				
	</div>
</div>

<script>

</script>

app/views/colleges/edit.html.erb
<%= render "form" %>

app/views/colleges/index.html.erb
<center><h2 class="text-danger">All Colleges</h2></center>

	<%= link_to "New College",new_college_path ,class: "btn btn-info btn-sm" %>
	<div class="container">
		<div class="table">
			<table class="table table-striped table-hover table-bordered">	
				<tr class="info">
					<th class="align">College Name </th>
					<th class="align">Email</th>
					<th class="align">Location</th>
					<th class= "align">Phone Number</th>
					<th colspan="5" class="align">Actions</th>
				</tr>
					
				<% @colleges.each do |college|%>
						
				<tr class="textcolor ">
					<td class="align"><%= college.name %></td>
					<td class="align"><%= college.email %></td>
					<td class="align"><%= college.location %></td>
					<td class="align"><%= college.phno %></td>
					<td class="align"><%= link_to "Edit",edit_college_path(college) %></td>
					<td class="align"><%= link_to "Delete",college,method: :delete ,data:{confirm: "Are you sure to delete?"}%></td> 
				</tr>

				<%end%>
			</table>
		</div>
	</div>

app/views/colleges/new.html.erb
<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rspec</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/_form.html.erb
<style>
	.clr{color:red;}
</style>

<div class="container">
<center><h2 class="text-danger">New Student</h2></center>
<hr/>
	<div class="form-horizontal">
		<%= form_for @student do |s| %>
			
			<div class="form-group ">
				<%= s.label :Student_Name,class:"control-label col-sm-3"%>
			<div class="col-sm-6">
				<%= s.text_field :name,class:"form-control",id:"title"%>
			</div>
			</div>

			<div>
			

			<div class="form-group">
				<%= s.label :Email,class:"control-label col-sm-3"%>
			<div class="col-sm-6">
				<%= s.email_field :email,class:"form-control"%>
			</div>
			</div>

		    <div class="form-group">
				<%= s.label :Colleges,class:"control-label col-sm-3" %>
			<div class="col-sm-6">
				<%= select("student", "college_id", @colleges.collect {|c| [ c.name, c.id ] },{prompt: "select college"},class:"form-control") %>
			</div>

			<div class="form-group"><br/><br/>
				<%= s.label :Age,class:"control-label col-sm-3"%>
			<div class="col-sm-6">
				<%= s.text_field :age,class:"form-control"%>
			</div>
			</div>

			<div class="form-group">
				<%= s.label :Date_Of_Birth,class:"control-label col-sm-3"%>
			<div class="col-sm-6">
				<%= s.text_field :dob,class:"form-control"%>
			</div>
			</div>



			<div class="form-group">
				<%= s.submit "Save",class:"col-sm-offset-3 btn btn-sm btn-info"%>
				<%= link_to "All Students",students_path,class:"btn btn-sm btn-info col-sm-offset-0"%>
			</div>	

		<%end%>

		<% if @student.errors.present? %>
		    <div id="error_explanation">
		      <h3 class="text-danger">
		        <%= pluralize(@student.errors.count, "error") %> prohibited
		        this article from being saved:
		      </h3>
		      
		      <ul>
		        <% @student.errors.full_messages.each do |msg| %>
		          <div class="alert alert-danger">
		          	<li><%= msg %></li>
		          </div>
		        <% end %>
		      </ul>
		    
		    </div>
  		<% end %>

				
	</div>
</div>

app/views/students/edit.html.erb
<%= render "form" %>

app/views/students/index.html.erb
<center><h2 class="text-danger">All Students</h2></center>

	<div class="container">
		<%= link_to "New Student",new_student_path ,class: "btn btn-info btn-sm" %>
		
		<br/><div class="table">
				<table class="table table-striped table-hover table-bordered">	
					<tr class="info">
						<th class="align">Student Name </th>
						<th class="align">College</th>
						<th class="align">Email</th>
						<th class="align">Date Of Birth</th>
						<th class= "align">Age</th>
						<th colspan="5" class="align">Actions</th>
					</tr>
					
					<% @students.each do |student|%>
						
						<tr class="textcolor ">
							<td class="align"><%= student.name %></td>
							<td class="align"><%= student.college.name if student.college %></td>
							<td class="align"><%=link_to student.email,student %></td>
							<td class="align"><%= student.dob %></td>
							<td class="align"><%= student.age %></td>
							<td class="align"><%= link_to "Edit",edit_student_path(student) %></td>
							<td class="align"><%= link_to "Delete",student,method: :delete ,data:{confirm: "Are you sure to delete?"}%></td> 
					<%end%>
						
				</table>
			</div>
	</div>

app/views/students/new.html.erb
<%= render "form" %>

app/views/students/show.html.erb
<div class="container">
	<center><h2 class="text-danger"><%= @student.name %></h2></center>
	<hr/>
	<h3 class="text-info">College: <%= @student.college.name %></h3><br/>
	<h4 class="text-success">Student Email:<%= @student.email %></h4>
	<h4 class="text-success">Date Of Birth:<%= @student.dob %></h4>
	<h4 class="text-success">Age:<%= @student.age %></h4>
	<h4 class="text-success">College Location:<%= @student.college.location %></h4>
	<h4 class="text-success">College Email:<%= @student.college.email %></h4>
	<h4 class="text-success">College Phone Number:<%= @student.college.phno %></h4>
	<%= link_to "Back" , students_path, class: "btn btn-sm btn-info"%>
</div>